OdeToFood/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

OdeToFood/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

OdeToFood/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

OdeToFood/Pages/Restaurants/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Data;
using OdeToFood.Core;

namespace OdeToFood.Pages.Restaurants
{
    public class DeleteModel : PageModel
    {
        private readonly IResturantData resturantData;

        public DeleteModel(IResturantData resturantData)
        {
            this.resturantData = resturantData;
        }

        public Restaurent Restaurent { get; set; }

        public IActionResult OnGet(int restarantId)
        {
            Restaurent = resturantData.GetById(restarantId);
            if(Restaurent == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public IActionResult OnPost(int restarantId)
        {
            var restaurant = resturantData.Delete(restarantId);
            resturantData.Commit();
            if(restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }
            TempData["Message"] = $"{ restaurant.Name} deleted";
            return RedirectToPage("./List");
        }
    }
}

OdeToFood/Pages/Restaurants/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restaurants
{
    public class DetailModel : PageModel
    {
        public Restaurent Restaurent { get; set; }
        public IResturantData ResturantData { get; }
        [TempData]
        public string Message { get; set; }

        public IActionResult OnGet(int restaurentId)
        {
            Restaurent = ResturantData.GetById(restaurentId);
            if(Restaurent == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public DetailModel(IResturantData resturantData)
        {
            ResturantData = resturantData;
        }
    }
}

OdeToFood/Pages/Restaurants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Data;
using OdeToFood.Core;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace OdeToFood.Pages.Restaurants
{
    public class EditModel : PageModel
    {

        private readonly IResturantData resturantData;
        private readonly IHtmlHelper htmlHelper;

        [BindProperty]
        public Restaurent Restaurent { get; set; }
        public IEnumerable<SelectListItem> Cuisines { get; set; }

        public EditModel(IResturantData resturantData, IHtmlHelper htmlHelper)
        {
            this.resturantData = resturantData;
            this.htmlHelper = htmlHelper;
        }


        public IActionResult OnGet(int? restaurentId)
        {
            Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();
            if(restaurentId.HasValue)
            {
                Restaurent = resturantData.GetById(restaurentId.Value);
            }
            else
            {
                Restaurent = new Restaurent();
            }
            if (Restaurent == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            if(!ModelState.IsValid)
            {
                Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();
                return Page();
            }
            if(Restaurent.Id > 0)
            {
                resturantData.Update(Restaurent);
            }
            else
            {
                resturantData.Add(Restaurent);
            }
            resturantData.Commit();
            TempData["Message"] = "Restaurant saved!";
            return RedirectToPage("./Detail", new { restaurentId = Restaurent.Id });
        }
    }
}

OdeToFood/Pages/Restaurants/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using OdeToFood.Data;
using OdeToFood.Core;

namespace OdeToFood.Pages.Restaurants
{
    public class ListModel : PageModel
    {
        private readonly IConfiguration config;
        public string Message { get; set; }
        public IEnumerable<Restaurent> Restaurents { get; set; }
        public IResturantData resturantData { get; }
            
        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }
        public ListModel(IConfiguration config, IResturantData resturantData)
        {
            this.config = config;
            this.resturantData = resturantData;
        }

        public void OnGet()
        {
            Message = config["Message"];
            Restaurents = resturantData.GetRestaruentsByName(SearchTerm);
        }

        
    }
}

OdeToFood/ViewComponents/RestaurantCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    public class RestaurantCountViewComponent
         : ViewComponent
    {
        private readonly IResturantData restaurantData;

        public RestaurantCountViewComponent(IResturantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }

        public IViewComponentResult Invoke()
        {
            var count = restaurantData.GetCountOfRestaurants();
            return View(count);
        }

    }
}

OdeToFood/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OdeToFood/Pages/Restaurants/Delete.cshtml
@page "{restarantId}"
@model OdeToFood.Pages.Restaurants.DeleteModel
@{

}


<div class="alert alert-danger">
    Are you sure you want to delete @Model.Restaurent.Name?
</div>
<form method="post">
    <button type="submit" class="btn btn-danger">Yes!</button>
    <a class="btn btn-primary" asp-page="List">Cancel</a>
</form>

OdeToFood/Pages/Restaurants/Detail.cshtml
@page "{restaurentId:int}"

@model OdeToFood.Pages.Restaurants.DetailModel
@{
    ViewData["Title"] = "Detail";
}

<h1>@Model.Restaurent.Name</h1>

<div>
    ID: @Model.Restaurent.Id
</div>
<div>
    Location: @Model.Restaurent.Location
</div>
<div>
    Cuisine: @Model.Restaurent.Cuisine
</div>

@if(Model.Message != null)
{
    <div class="alert alert-info">@Model.Message</div>
}

<a asp-page="./List" class="btn btn-light">All Restaurants</a>

OdeToFood/Pages/Restaurants/Edit.cshtml
@page "{restaurentId:int?}"

@model OdeToFood.Pages.Restaurants.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Editing @Model.Restaurent.Name</h1>

<form method="post">
    <input type="hidden" asp-for="Restaurent.Id" />
    <div class="form-group">
        <label asp-for="Restaurent.Name"></label>
        <input asp-for="Restaurent.Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurent.Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Restaurent.Location"></label>
        <input asp-for="Restaurent.Location" class="form-control" />
        <span class="text-danger" asp-validation-for="Restaurent.Location"></span>
    </div>
    <div class="form-group">
        <label asp-for="Restaurent.Cuisine"></label>
        <select asp-for="Restaurent.Cuisine" asp-items="@Model.Cuisines" class="form-control"></select>
        <span class="text-danger" asp-validation-for="Restaurent.Cuisine"></span>
    </div>

    <button class="btn  btn-primary" type="submit">Save</button>
</form>

OdeToFood/Pages/Restaurants/List.cshtml
@page
@model OdeToFood.Pages.Restaurants.ListModel
@{
    ViewData["Title"] = "Restaurants";
}

<h1>Restaurants</h1>

<form method="get">
    <div class="form-group">
        <div class="input-group">
            <input type="search" class="form-control" asp-for="SearchTerm" />
            <span class="input-group-btn">
                <button class="btn btn-light">
                    <i class="glyphicon glyphicon-search">Search</i>
                </button>
            </span>
        </div>
    </div>
</form>

@foreach (var resraurant in Model.Restaurents)
{
    <partial name="_Summary" model="resraurant" />
}

<a asp-page="./Edit" class="btn btn-primary">Add New</a>

@section footer{
    <div>@Model.Message</div>
}

OdeToFood/Pages/Restaurants/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h1>Your Restaurant was not found</h1>
<a asp-page="./List" class="btn btn-primary">See all Restaurants</a>

OdeToFood/Pages/Restaurants/_Summary.cshtml
@using OdeToFood.Core
@model Restaurent


    <div class="card card-header">
        <h3>@Model.Name</h3>
    </div>
    <div class="card card-body">
        <span>Location: @Model.Location</span>
        <span>Cuisine: @Model.Cuisine</span>
    </div>
    <div class="card card-footer">
        <a class="btn btn-light" asp-page="./Detail" asp-route-restaurentId="@Model.Id">
            <i class="glyphicon glyphicon-zoom-in">Details</i>
        </a>
        <a class="btn btn-info" asp-page="./Edit" asp-route-restaurentId="@Model.Id">
            <i class="glyphicon glyphicon-zoom-in">Edit</i>
        </a>
        <a class="btn btn-danger" asp-page="./Delete" asp-route-restaurentId="@Model.Id">
            <i class="glyphicon glyphicon-zoom-in">Delete</i>
        </a>
    </div>

OdeToFood/Pages/Shared/Components/RestaurantCount/Default.cshtml
@model int 

    <div class="well">
        There are @Model restarrants here. <a asp-page="/Restaurants/List">See them all here </a> 
    </div> 

OdeToFood/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OdeToFood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OdeToFood</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Restaurants/List">Restaurants</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <vc:restaurant-count></vc:restaurant-count>
            @RenderSection("footer", required: false)
            &copy; 2020 - OdeToFood - <a asp-area="" asp-page="/Privacy">Privacy</a>

        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>